<?php
$test_str1=<<<JSON_STR1
{"location":"200 BAY ST ","subCode":10037,"folderName":"200 BAY ST, SUITE 1301","workCode":10048,"folderDescription":"Proposal to construct a new demising wall and new entrance door in existing office that will be divided in 2 offices, unit 1301. ","folderCondition":"[[BUILDING CODE ATTRIBUTE exists for this property. To view record go to BUILDING CODE ATTRIBUTE application.]] [[BUILDING CODE ATTRIBUTE exists for this property. To view record go to BUILDING CODE ATTRIBUTE application.]] <<>>","propertyLocation":"PLAN D24 LOTS 1 TO 9 PLAN 181E LOTS A TO G PT TOWN LOTS 5 & 6 RP 66R7740 PARTS 1 TO 10 **Pre Dec 2018 GRID#S2809 **GRID S1034","propertyRsn":"206973","mainProperty":{"direction":"","region":"S1034","streetType":"ST","city":"TORONTO","propertyRsn":206973,"province":"ON","postal":"","propX":0.0,"propY":0.0,"house":"200","street":"BAY","wardDesc":"Ward 10: Spadina-Fort York","propertyRoll":"1904061160014000000","legalDesc":"PLAN D24 LOTS 1 TO 9 PLAN 181E LOTS A TO G PT TOWN LOTS 5 & 6 RP 66R7740 PARTS 1 TO 10"},"workDesc":"Interior Alterations","subDesc":"Office","issueDate":"Aug 20, 2019","issueUser":"JKISSOO2","issueUserName":"---","issueUserTitle":"---","issueUserContact":"---","inspectionProcesses":[{"startDate":"","endDate":"","folderRsn":"4625661","statusDesc":"Open","processRsn":"63082102","processCode":"10608","disciplineDesc":"Inspection","assignedUserTitle":"Building Specialist","processDesc":"BA Building Inspection Pt3","assignedUserDesc":"Chin Lue, Norman","assignedUserLocation":"95 The Esplanade, Gr. Floor, Lower Level","assignedUserDepartment":"Toronto and East York - Inspections","assignedUserContact":"(416) 338-5761","assignedUserEmail":"Norman.ChinLue@toronto.ca","assignedUserFax":"(416) 696-4151","assignedUserDistrictPhone":"416-338-0700","assignedUserDistrictEmail":"TOBldgInsp@toronto.ca","assignedUserDistrictFax":"416-696-4151","folderProcessAttempts":[]}],"applicationNum":"19 202062 BLD 00 BA","locationExt":"200 BAY ST <br/>TORONTO ON <br/>Ward 10: Spadina-Fort York","showStatus":true,"originalPermit":"","showSignCommitteeLink":false,"showOrder":false,"statusCode":20,"folderYear":"19","folderSequence":"202062","folderRsn":"4625661","folderType":"BA","folderSection":"BLD","folderRevision":"00","statusDesc":"Permit Issued","inDate":"Aug 7, 2019","folderTypeDesc":"Building Additions/Alterations"}
JSON_STR1;

$test_str2=<<<JSON_STR2
{"location":"18 KINGSMILL RD ","subCode":10077,"folderName":"18 KINGSMILL RD","workCode":10062,"folderDescription":"HVAC -  Proposal to rebuild/modify existing detached garage","folderCondition":"<<>>","propertyLocation":"PLAN 1686 PT LOTS 152 & 153 **Pre Dec 2018 GRID#W0503  **GRID W0322","propertyRsn":"494151","mainProperty":{"direction":"","region":"W0322","streetType":"RD","city":"TORONTO","propertyRsn":494151,"province":"ON","postal":"M8X 2N8","propX":0.0,"propY":0.0,"house":"18","street":"KINGSMILL","wardDesc":"Ward 3: Etobicoke-Lakeshore","propertyRoll":"1919011330016000000","legalDesc":"PLAN 1686 PT LOTS 152 & 153"},"workDesc":"Building Permit Related(MS)","subDesc":"SFD - Detached","issueDate":"Mar 26, 2019","issueUser":"DBEECH","issueUserName":"---","issueUserTitle":"---","issueUserContact":"---","inspectionProcesses":[{"startDate":"","endDate":"","folderRsn":"4540722","statusDesc":"Open","processRsn":"61695985","processCode":"10616","disciplineDesc":"Inspection","assignedUserTitle":"Inspector Generalist","processDesc":"MS HVAC Inspection H","assignedUserDesc":"Borromeo, Frank","assignedUserLocation":"2 Civic Centre Crt., 2nd Floor","assignedUserDepartment":"Etobicoke York - Inspections","assignedUserContact":"(416) 394-8047","assignedUserEmail":"Frank.Borromeo@toronto.ca","assignedUserFax":"(416) 696-4169","assignedUserDistrictPhone":"416-394-8055","assignedUserDistrictEmail":"ETBldgInsp@toronto.ca","assignedUserDistrictFax":"416-696-4169","folderProcessAttempts":[]}],"applicationNum":"18 186670 HVA 00 MS","locationExt":"18 KINGSMILL RD <br/>TORONTO ON M8X 2N8<br/>Ward 3: Etobicoke-Lakeshore","showStatus":true,"originalPermit":"","showSignCommitteeLink":false,"showOrder":false,"statusCode":20,"folderYear":"18","folderSequence":"186670","folderRsn":"4540722","folderType":"MS","folderSection":"HVA","folderRevision":"00","statusDesc":"Permit Issued","inDate":"Mar 20, 2019","folderTypeDesc":"Mechanical(MS)"}
JSON_STR2;

$data_descr=json_decode($test_str1);
var_dump($data_descr);
echo $data_descr->folderDescription."\n";
?>